[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"

[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-gatsby"